import { Assistant } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import Navbar from "@/components/Trade/Navbar";
import Footer from "@/components/Trade/Footer";

const assistantFont = Assistant({
  weight: ['400', '500','600','700', '800'],
  subsets: ["latin"],
  display: 'swap'
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${assistantFont.className} antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar/>
        {children}
        <Toaster richColors position="top-right" />
        <Footer/>
      </body>
    </html>
  );
}
